name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [1,2,3,4,5,6,7,8,9,10]
        b: [1,2,3,4,5,6,7,8,9,10]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip requests
    - name: Run A
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        python3 keep_docker_hub_images.py ${{ matrix.a }} ${{ matrix.b }}
    - name: Run B
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        python3 replicate_v2_docker_images.py ${{ matrix.a }} ${{ matrix.b }}
